Repository TeamWeathy/WeathyiOS, pull requests merged in 2021-02, with the labels that each got.

#80 [fix] User관련 Struct 재설정
  Weathy/Podfile.lock
  Weathy/Weathy.xcodeproj/project.pbxproj
  Weathy/Weathy/Sources/Models/User.swift
  Weathy/Weathy/Sources/Models/UserInformation/UserInformation.swift
Labels: 🔧 fix, 🚨 bug

#81 network struct 구조 통일
  Weathy/Podfile.lock
  Weathy/Weathy.xcodeproj/project.pbxproj
  Weathy/Weathy/Resources/AppDelegate.swift
  Weathy/Weathy/Sources/Cells/Main/MainTopCVC.swift
  Weathy/Weathy/Sources/Cells/Main/TimezoneWeatherCVC.swift
  Weathy/Weathy/Sources/Cells/Main/WeeklyWeatherCVC.swift
  Weathy/Weathy/Sources/Models/Calendar/DailyWeathyData.swift
  Weathy/Weathy/Sources/Models/Calendar/MonthlyWeathyData.swift
  Weathy/Weathy/Sources/Models/CalendarOverview.swift
  Weathy/Weathy/Sources/Models/Climate.swift
  Weathy/Weathy/Sources/Models/Closet.swift
  Weathy/Weathy/Sources/Models/DailyWeather.swift
  Weathy/Weathy/Sources/Models/DateClass.swift
  Weathy/Weathy/Sources/Models/ExtraWeather.swift
  Weathy/Weathy/Sources/Models/HighLowTemp.swift
  Weathy/Weathy/Sources/Models/HourlyWeather.swift
  Weathy/Weathy/Sources/Models/Main/DailyWeatherData.swift
  Weathy/Weathy/Sources/Models/Main/ExtraWeatherData.swift
  Weathy/Weathy/Sources/Models/Main/HourlyWeatherData.swift
  Weathy/Weathy/Sources/Models/Main/LocationWeatherData.swift
  Weathy/Weathy/Sources/Models/Main/RecommededWeathyData.swift
  Weathy/Weathy/Sources/Models/OverviewWeather.swift
  Weathy/Weathy/Sources/Models/Record/ClothesTagData.swift
  Weathy/Weathy/Sources/Models/Region.swift
  Weathy/Weathy/Sources/Models/SearchInformation/SearchWeatherInformation.swift
  Weathy/Weathy/Sources/Models/WeathyClass.swift
  Weathy/Weathy/Sources/VCs/Calendar/CalendarDetailVC.swift
  Weathy/Weathy/Sources/VCs/Main/MainVC.swift
  Weathy/Weathy/Sources/VCs/MainSearch/MainSearchVC.swift
  Weathy/Weathy/Sources/VCs/ModifyWeathy/ModifyWeathyNVC.swift
  Weathy/Weathy/Sources/VCs/ModifyWeathy/ModifyWeathyRateVC.swift
  Weathy/Weathy/Sources/VCs/ModifyWeathy/ModifyWeathyStartVC.swift
  Weathy/Weathy/Sources/VCs/ModifyWeathy/ModifyWeathyTagVC.swift
  Weathy/Weathy/Sources/VCs/ModifyWeathy/ModifyWeathyTextVC.swift
  Weathy/Weathy/Sources/VCs/Record/RecordStartVC.swift
  Weathy/Weathy/Sources/VCs/Record/RecordTagAddPopupVC.swift
  Weathy/Weathy/Sources/VCs/Record/RecordTagDeletePopupVC.swift
  Weathy/Weathy/Sources/VCs/Record/RecordTagVC.swift
Labels: 🌈 refactor, 📞 network, 🔧 fix

#82 [Feat/72] 작은 기기 대응 완료
  Weathy/Weathy.xcodeproj/project.pbxproj
  Weathy/Weathy/Resources/APIServices/Main/MainService.swift
  Weathy/Weathy/Resources/Storyboards/Main/Main.storyboard
  Weathy/Weathy/Sources/Cells/Main/MainTopCVC.swift
  Weathy/Weathy/Sources/Classes/LocationManager.swift
  Weathy/Weathy/Sources/VCs/Main/MainVC.swift
Labels: ✨ style, 인애, 🌈 refactor, 🔧 fix

#85 [Feat/74] 눈, 비 한꺼번에 내리는 이슈 해결
  Weathy/Weathy.xcodeproj/xcshareddata/xcschemes/Weathy.xcscheme
  Weathy/Weathy/Sources/VCs/Main/MainVC.swift
Labels: 🔧 fix, 🚨 bug

#86 [Feat/75] 캘린더 뷰 데이터 전달
  Weathy/Weathy/Resources/Storyboards/Main/Main.storyboard
  Weathy/Weathy/Sources/Extensions/Date+Extensions.swift
  Weathy/Weathy/Sources/VCs/Main/MainVC.swift
Labels: 🌿 feature

#93 [Feat/87] timezone CV 블러바 기능 추가
  Weathy/Weathy/Resources/Assets.xcassets/mainscrollTimeBoxBlur.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/mainscrollTimeBoxBlur.imageset/mainscrollTimeBoxBlur.png
  Weathy/Weathy/Resources/Assets.xcassets/mainscrollTimeBoxBlur.imageset/mainscrollTimeBoxBlur@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/mainscrollTimeBoxBlur.imageset/mainscrollTimeBoxBlur@3x.png
  Weathy/Weathy/Resources/Storyboards/Main/Main.storyboard
  Weathy/Weathy/Sources/VCs/Main/MainVC.swift
Labels: ✨ style, 🌿 feature

#118 [Feat/90] GPS 로직 구현 완료
  Weathy/Weathy.xcodeproj/project.pbxproj
  Weathy/Weathy/Info.plist
  Weathy/Weathy/Resources/APIServices/APIConstants.swift
  Weathy/Weathy/Resources/APIServices/Main/MainService.swift
  Weathy/Weathy/Resources/AppDelegate.swift
  Weathy/Weathy/Sources/Classes/LocationManager.swift
  Weathy/Weathy/Sources/Extensions/Date+Extensions.swift
  Weathy/Weathy/Sources/Extensions/UserDefaults+Extensions.swift
  Weathy/Weathy/Sources/VCs/Main/MainVC.swift
  Weathy/Weathy/Sources/VCs/MainSearch/MainSearchVC.swift
  Weathy/Weathy/Sources/VCs/OnBoarding/NickNameVC.swift
  Weathy/Weathy/Sources/VCs/Record/RecordStartVC.swift
Labels: 🔧 fix

#123 [Feat/83] 오늘의 추천 웨디 사진, 글 아이콘 추가
  Weathy/Weathy/Resources/APIServices/APIConstants.swift
  Weathy/Weathy/Resources/Assets.xcassets/mainIcImage.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/mainIcImage.imageset/mainIcImage.png
  Weathy/Weathy/Resources/Assets.xcassets/mainIcImage.imageset/mainIcImage@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/mainIcImage.imageset/mainIcImage@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/mainIcText.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/mainIcText.imageset/mainIcText.png
  Weathy/Weathy/Resources/Assets.xcassets/mainIcText.imageset/mainIcText@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/mainIcText.imageset/mainIcText@3x.png
  Weathy/Weathy/Resources/Storyboards/Main/Main.storyboard
  Weathy/Weathy/Sources/Cells/Main/WeeklyWeatherCVC.swift
  Weathy/Weathy/Sources/Models/Common/ClimateImage.swift
  Weathy/Weathy/Sources/Models/DailyWeather.swift
  Weathy/Weathy/Sources/Models/WeathyClass.swift
  Weathy/Weathy/Sources/VCs/Main/MainVC.swift
Labels: 🌿 feature, 📞 network

#124 [Feat/119] 웨디 시작하기 버튼 누른 후 위치 권한 받아오기
  Weathy/Weathy/Sources/Classes/LocationManager.swift
  Weathy/Weathy/Sources/VCs/OnBoarding/NickNameVC.swift
  Weathy/Weathy/Sources/VCs/OnBoarding/OnBoardingFirstVC.swift
Labels: 인애, 🔧 fix

#126 [Feat/92] 메인 일러 애니메이션 추가
  Weathy/Weathy/Resources/Assets.xcassets/mainscrollBoxTopblurNight.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/mainscrollBoxTopblurNight.imageset/mainscrollBoxTopblurNight.png
  Weathy/Weathy/Resources/Assets.xcassets/mainscrollBoxTopblurNight.imageset/mainscrollBoxTopblurNight@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/mainscrollBoxTopblurNight.imageset/mainscrollBoxTopblurNight@3x.png
  Weathy/Weathy/Sources/Classes/LocationManager.swift
  Weathy/Weathy/Sources/VCs/Main/MainVC.swift
Labels: ✨ style, 인애

#143 [Feat/125] 닉네임 뷰 레이아웃 수정 및 플로우 구현
  Weathy/Weathy.xcodeproj/project.pbxproj
  Weathy/Weathy/Resources/Assets.xcassets/accessCustomDiv.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/accessCustomDiv.imageset/accessCustomDiv.png
  Weathy/Weathy/Resources/Assets.xcassets/accessCustomDiv.imageset/accessCustomDiv@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/accessCustomDiv.imageset/accessCustomDiv@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/accessCustomIcCamera.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/accessCustomIcCamera.imageset/accessCustomIcCamera.png
  Weathy/Weathy/Resources/Assets.xcassets/accessCustomIcCamera.imageset/accessCustomIcCamera@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/accessCustomIcCamera.imageset/accessCustomIcCamera@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/accessCustomIcGps.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/accessCustomIcGps.imageset/accessCustomIcGps.png
  Weathy/Weathy/Resources/Assets.xcassets/accessCustomIcGps.imageset/accessCustomIcGps@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/accessCustomIcGps.imageset/accessCustomIcGps@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/accessCustomIcOption.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/accessCustomIcOption.imageset/accessCustomIcOption.png
  Weathy/Weathy/Resources/Assets.xcassets/accessCustomIcOption.imageset/accessCustomIcOption@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/accessCustomIcOption.imageset/accessCustomIcOption@3x.png
  Weathy/Weathy/Resources/Storyboards/OnBoarding/OnBoarding.storyboard
  Weathy/Weathy/Sources/Classes/LocationManager.swift
  Weathy/Weathy/Sources/Extensions/UIFont+Extension.swift
  Weathy/Weathy/Sources/VCs/OnBoarding/NickNamePopUpVC.swift
  Weathy/Weathy/Sources/VCs/OnBoarding/NickNameVC.swift
Labels: ✨ style, 인애, 🔧 fix

#153 [Feat/145] 스크롤 버그 및 메인 서버 refresh
  Weathy/Weathy/Resources/Storyboards/Main/Main.storyboard
  Weathy/Weathy/Sources/Cells/Main/TimezoneWeatherCVC.swift
  Weathy/Weathy/Sources/VCs/Main/MainVC.swift
  Weathy/Weathy/Sources/VCs/Tabbar/TabbarVC.swift
Labels: 🚨 bug

#158 [Feat/157] 온보딩 레이아웃 수정
  Weathy/Weathy/Resources/Assets.xcassets/onboardingImgPopup1.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/onboardingImgPopup1.imageset/onboardingImgPopup1.png
  Weathy/Weathy/Resources/Assets.xcassets/onboardingImgPopup1.imageset/onboardingImgPopup1@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/onboardingImgPopup1.imageset/onboardingImgPopup1@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/onboardingImgPopup2.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/onboardingImgPopup2.imageset/onboardingImgPopup2.png
  Weathy/Weathy/Resources/Assets.xcassets/onboardingImgPopup2.imageset/onboardingImgPopup2@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/onboardingImgPopup2.imageset/onboardingImgPopup2@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/onboardingImgPopup3.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/onboardingImgPopup3.imageset/onboardingImgPopup3.png
  Weathy/Weathy/Resources/Assets.xcassets/onboardingImgPopup3.imageset/onboardingImgPopup3@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/onboardingImgPopup3.imageset/onboardingImgPopup3@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/onboarding_blur.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/onboarding_blur.imageset/onboarding_blur.png
  Weathy/Weathy/Resources/Assets.xcassets/onboarding_img_phone1.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/onboarding_img_phone1.imageset/onboarding_img_phone1.png
  Weathy/Weathy/Resources/Assets.xcassets/onboarding_img_phone2.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/onboarding_img_phone2.imageset/onboarding_img_phone2.png
  Weathy/Weathy/Resources/Assets.xcassets/onboarding_img_phone3.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/onboarding_img_phone3.imageset/onboarding_img_phone3.png
  Weathy/Weathy/Resources/Assets.xcassets/onboarding_img_phone_1.imageset/onboarding_img_phone_1.png
  Weathy/Weathy/Resources/Assets.xcassets/onboarding_img_phone_1.imageset/onboarding_img_phone_1@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/onboarding_img_phone_1.imageset/onboarding_img_phone_1@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/onboarding_img_phone_2.imageset/onboarding_img_phone_2.png
  Weathy/Weathy/Resources/Assets.xcassets/onboarding_img_phone_2.imageset/onboarding_img_phone_2@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/onboarding_img_phone_2.imageset/onboarding_img_phone_2@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/onboarding_img_phone_3.imageset/onboarding_img_phone_3.png
  Weathy/Weathy/Resources/Assets.xcassets/onboarding_img_phone_3.imageset/onboarding_img_phone_3@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/onboarding_img_phone_3.imageset/onboarding_img_phone_3@3x.png
  Weathy/Weathy/Resources/Storyboards/OnBoarding/OnBoarding.storyboard
  Weathy/Weathy/Sources/Extensions/UIFont+Extension.swift
  Weathy/Weathy/Sources/VCs/OnBoarding/OnBoardingFirstVC.swift
Labels: ✨ style

#163 [Feat/159] 설정 뷰 레이아웃
  Weathy/Weathy/Resources/Storyboards/Main/Main.storyboard
  Weathy/Weathy/Resources/Storyboards/ModifyWeathy/ModifyWeathyRate.storyboard
  Weathy/Weathy/Resources/Storyboards/ModifyWeathy/ModifyWeathyStart.storyboard
  Weathy/Weathy/Resources/Storyboards/ModifyWeathy/ModifyWeathyTag.storyboard
  Weathy/Weathy/Resources/Storyboards/ModifyWeathy/ModifyWeathyText.storyboard
  Weathy/Weathy/Resources/Storyboards/Record/RecordRate.storyboard
  Weathy/Weathy/Resources/Storyboards/Record/RecordStart.storyboard
  Weathy/Weathy/Resources/Storyboards/Record/RecordTag.storyboard
  Weathy/Weathy/Resources/Storyboards/Setting/Setting.storyboard
  Weathy/Weathy/Sources/Extensions/UIViewController+Extension.swift
  Weathy/Weathy/Sources/VCs/Setting/ChangeNickNameVC.swift
  Weathy/Weathy/Sources/VCs/Setting/SettingVC.swift
Labels: 🔧 fix

#176 [Feat/170] helpButton 백그라운드 액션 막기
  Weathy/Weathy/Resources/AppDelegate.swift
  Weathy/Weathy/Sources/Cells/Main/MainTopCVC.swift
  Weathy/Weathy/Sources/Models/SearchInformation/SearchWeatherInformation.swift
  Weathy/Weathy/Sources/VCs/Main/MainVC.swift
  Weathy/Weathy/Sources/VCs/MainSearch/MainSearchVC.swift
  Weathy/Weathy/Sources/VCs/Record/RecordStartVC.swift
Labels: 🔧 fix
