Repository TeamWeathy/WeathyiOS, pull requests merged in 2021-01, with the labels that each got.

#8 Feat/4
  Weathy/Podfile.lock
  Weathy/Weathy.xcodeproj/project.pbxproj
  Weathy/Weathy/Info.plist
  Weathy/Weathy/Resources/Assets.xcassets/?.imageset/?.png
  Weathy/Weathy/Resources/Assets.xcassets/?.imageset/?@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/?.imageset/?@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/?.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/btnDelete.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/btnDelete.imageset/btnDelete.png
  Weathy/Weathy/Resources/Assets.xcassets/btnDelete.imageset/btnDelete@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/btnDelete.imageset/btnDelete@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/settingBtnEditSelected.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/settingBtnEditSelected.imageset/settingBtnEditSelected.png
  Weathy/Weathy/Resources/Assets.xcassets/settingBtnEditSelected.imageset/settingBtnEditSelected@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/settingBtnEditSelected.imageset/settingBtnEditSelected@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/settingBtnEditUnselected.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/settingBtnEditUnselected.imageset/settingBtnEditUnselected.png
  Weathy/Weathy/Resources/Assets.xcassets/settingBtnEditUnselected.imageset/settingBtnEditUnselected@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/settingBtnEditUnselected.imageset/settingBtnEditUnselected@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/settingDivGrey.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/settingDivGrey.imageset/settingDivGrey.png
  Weathy/Weathy/Resources/Assets.xcassets/settingDivGrey.imageset/settingDivGrey@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/settingDivGrey.imageset/settingDivGrey@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/settingFrameArrow.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/settingFrameArrow.imageset/settingFrameArrow.png
  Weathy/Weathy/Resources/Assets.xcassets/settingFrameArrow.imageset/settingFrameArrow@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/settingFrameArrow.imageset/settingFrameArrow@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/settingImgTextfieldSelected.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/settingImgTextfieldSelected.imageset/settingImgTextfieldSelected.png
  Weathy/Weathy/Resources/Assets.xcassets/settingImgTextfieldSelected.imageset/settingImgTextfieldSelected@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/settingImgTextfieldSelected.imageset/settingImgTextfieldSelected@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/settingImgTextfieldUnselected.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/settingImgTextfieldUnselected.imageset/settingImgTextfieldUnselected.png
  Weathy/Weathy/Resources/Assets.xcassets/settingImgTextfieldUnselected.imageset/settingImgTextfieldUnselected@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/settingImgTextfieldUnselected.imageset/settingImgTextfieldUnselected@3x.png
  Weathy/Weathy/Resources/Storyboards/Setting.storyboard
  Weathy/Weathy/Resources/Storyboards/Tabbar/Tabbar.storyboard
  Weathy/Weathy/Sources/VCs/SettingVCs/AskForVC.swift
  Weathy/Weathy/Sources/VCs/SettingVCs/ChangeNickNameVC.swift
  Weathy/Weathy/Sources/VCs/SettingVCs/DevelopersInfoVC.swift
  Weathy/Weathy/Sources/VCs/SettingVCs/SettingNVC.swift
  Weathy/Weathy/Sources/VCs/SettingVCs/SettingVC.swift
  Weathy/Weathy/Sources/VCs/TabbarVCs/ExampleFirstVC.swift
  Weathy/Weathy/Sources/VCs/TabbarVCs/ExampleSecondVC.swift
  Weathy/Weathy/Sources/VCs/TabbarVCs/ExampleThirdVC.swift
  Weathy/Weathy/Sources/VCs/TabbarVCs/TabbarVC.swift
Labels: ⛱ view, ✌🏼 priority: middle, ✨ style, 황호, 🌿 feature, 🔧 fix

#9 ReadMe 수정
  README.md
Labels: 황호, 📚 documentation

#23 [update] 전체 flow 연결
  Weathy/Weathy.xcodeproj/project.pbxproj
  Weathy/Weathy/Info.plist
  Weathy/Weathy/Resources/Storyboards/Record/RecordStart.storyboard
  Weathy/Weathy/Sources/VCs/Main/MainVC.swift
  Weathy/Weathy/Sources/VCs/Record/RecordNVC.swift
  Weathy/Weathy/Sources/VCs/Record/RecordStartVC.swift
  Weathy/Weathy/Sources/VCs/Tabbar/TabbarVC.swift
Labels: ✌🏼 priority: middle, 황호, 🔧 fix

#24 [chore] Foldering 했음
  Weathy/Weathy.xcodeproj/project.pbxproj
  Weathy/Weathy/Resources/Storyboards/MainSearch/MainSearch.storyboard
  Weathy/Weathy/Resources/Storyboards/OnBoarding/OnBoarding.storyboard
  Weathy/Weathy/Resources/Storyboards/Setting/Setting.storyboard
  Weathy/Weathy/Sources/VCs/MainSearch/MainSearchVC.swift
  Weathy/Weathy/Sources/VCs/Tabbar/ExampleFirstVC.swift
  Weathy/Weathy/Sources/VCs/Tabbar/ExampleSecondVC.swift
  Weathy/Weathy/Sources/VCs/Tabbar/ExampleThirdVC.swift
Labels: ☝🏼 prirority: low, 황호, 🔧 fix

#25 Feat/22
  Weathy/Weathy.xcodeproj/project.pbxproj
  Weathy/Weathy/Info.plist
  Weathy/Weathy/Resources/APIServices/APIConstants.swift
  Weathy/Weathy/Resources/APIServices/AuthorizationAPI/autoLoginService.swift
  Weathy/Weathy/Resources/APIServices/UserAPI/createUserService.swift
  Weathy/Weathy/Resources/APIServices/UserAPI/modifyUserService.swift
  Weathy/Weathy/Resources/Storyboards/OnBoarding/OnBoarding.storyboard
  Weathy/Weathy/Sources/Models/UserInformation/UserInformation.swift
  Weathy/Weathy/Sources/VCs/OnBoarding/NickNameVC.swift
  Weathy/Weathy/Sources/VCs/OnBoarding/OnBoardingFirstVC.swift
  Weathy/Weathy/Sources/VCs/Setting/ChangeNickNameVC.swift
  Weathy/Weathy/Sources/VCs/Tabbar/TabbarVC.swift
Labels: ✋🏼 priority: high, 황호, 📞 network

#28 Feat/26
  Weathy/Weathy.xcodeproj/project.pbxproj
  Weathy/Weathy/Resources/APIServices/APIConstants.swift
  Weathy/Weathy/Resources/APIServices/searchService.swift
  Weathy/Weathy/Resources/Assets.xcassets/nickname_btn_start.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/nickname_btn_start.imageset/nickname_btn_start.png
  Weathy/Weathy/Resources/Assets.xcassets/nickname_btn_start.imageset/nickname_btn_start@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/nickname_btn_start.imageset/nickname_btn_start@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/nickname_btn_start_mint.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/nickname_btn_start_mint.imageset/nickname_btn_start_mint.png
  Weathy/Weathy/Resources/Assets.xcassets/nickname_btn_start_mint.imageset/nickname_btn_start_mint@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/nickname_btn_start_mint.imageset/nickname_btn_start_mint@3x.png
  Weathy/Weathy/Resources/Storyboards/OnBoarding/OnBoarding.storyboard
  Weathy/Weathy/Sources/Models/SearchInformation/SearchWeatherInformation.swift
  Weathy/Weathy/Sources/VCs/MainSearch/MainSearchVC.swift
  Weathy/Weathy/Sources/VCs/OnBoarding/NickNameVC.swift
Labels: ✋🏼 priority: high, 황호, 📞 network

#30 Feat/20: Main 상단 뷰 서버 연동 (현재 날씨 + 오늘의 웨디)
  Weathy/Weathy.xcodeproj/project.pbxproj
  Weathy/Weathy/Resources/APIServices/APIConstants.swift
  Weathy/Weathy/Resources/APIServices/Main/MainService.swift
  Weathy/Weathy/Resources/Assets.xcassets/mainImgFewcloudsDay.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/mainImgFewcloudsDay.imageset/mainImgFewcloudsDay.png
  Weathy/Weathy/Resources/Assets.xcassets/mainImgFewcloudsDay.imageset/mainImgFewcloudsDay@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/mainImgFewcloudsDay.imageset/mainImgFewcloudsDay@3x.png
  Weathy/Weathy/Resources/Storyboards/Main/Main.storyboard
  Weathy/Weathy/Sources/Cells/Main/MainTopCVC.swift
  Weathy/Weathy/Sources/Models/Common/Emoji.swift
  Weathy/Weathy/Sources/Models/Main/LocationWeatherData.swift
  Weathy/Weathy/Sources/Models/Main/RecommededWeathy.swift
  Weathy/Weathy/Sources/VCs/Main/MainVC.swift
Labels: ✋🏼 priority: high, 인애, 📞 network

#33 Feat/16
  Weathy/Weathy.xcodeproj/project.pbxproj
  Weathy/Weathy/Info.plist
  Weathy/Weathy/Resources/APIServices/APIConstants.swift
  Weathy/Weathy/Resources/APIServices/Calendar/DailyWeathyService.swift
  Weathy/Weathy/Resources/APIServices/Calendar/DeleteWeathyService.swift
  Weathy/Weathy/Resources/APIServices/Calendar/MonthlyWeathyService.swift
  Weathy/Weathy/Resources/Assets.xcassets/calendarImgBeforeCloud.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/calendarImgNoContentCloud.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/calendarImgNoContentCloud.imageset/calendarImgNoContentCloud.png
  Weathy/Weathy/Resources/Assets.xcassets/calendarImgNoContentCloud.imageset/calendarImgNoContentCloud@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/calendarImgNoContentCloud.imageset/calendarImgNoContentCloud@3x.png
  Weathy/Weathy/Resources/Storyboards/Calendar.storyboard
  Weathy/Weathy/Sources/Cells/Calendar/InfiniteMonthlyCVC.swift
  Weathy/Weathy/Sources/Cells/Calendar/InfiniteWeeklyCVC.swift
  Weathy/Weathy/Sources/Cells/Calendar/MonthlyCalendarCVC.swift
  Weathy/Weathy/Sources/Cells/Calendar/WeeklyCalendarCVC.swift
  Weathy/Weathy/Sources/Extensions/Date+Extensions.swift
  Weathy/Weathy/Sources/Extensions/UIViewContoller+Extensions.swift
  Weathy/Weathy/Sources/Models/Calendar/DailyWeathyData.swift
  Weathy/Weathy/Sources/Models/Calendar/DeleteWeathyData.swift
  Weathy/Weathy/Sources/Models/Calendar/MonthlyWeathyData.swift
  Weathy/Weathy/Sources/Models/Common/Emoji.swift
  Weathy/Weathy/Sources/VCs/Calendar/CalendarDetailVC.swift
  Weathy/Weathy/Sources/VCs/Calendar/CalendarVC.swift
Labels: 예슬, 📞 network

#37 [update] 수정, 기록뷰로 데이터 전달
  Weathy/Weathy/Sources/VCs/Calendar/CalendarDetailVC.swift
Labels: 🌿 feature

#40 [update] search box cell 선택
  Weathy/Weathy.xcodeproj/project.pbxproj
  Weathy/Weathy/Info.plist
  Weathy/Weathy/Resources/APIServices/searchService.swift
  Weathy/Weathy/Resources/Storyboards/MainSearch/MainSearch.storyboard
  Weathy/Weathy/Resources/Storyboards/OnBoarding/OnBoarding.storyboard
  Weathy/Weathy/Sources/Cells/MainSearchTVCells/RecentTVC.swift
  Weathy/Weathy/Sources/Models/SearchInformation/SearchRecentInfo.swift
  Weathy/Weathy/Sources/Models/SearchInformation/SearchWeatherInformation.swift
  Weathy/Weathy/Sources/VCs/Main/MainVC.swift
  Weathy/Weathy/Sources/VCs/MainSearch/MainSearchVC.swift
  Weathy/Weathy/Sources/VCs/OnBoarding/NickNameVC.swift
  Weathy/Weathy/Sources/VCs/Splash/SplashVC.swift
Labels: ✋🏼 priority: high, 황호, 📞 network

#51 Feat/41
  Weathy/Podfile.lock
  Weathy/Weathy.xcodeproj/project.pbxproj
  Weathy/Weathy/Info.plist
  Weathy/Weathy/Resources/AppDelegate.swift
  Weathy/Weathy/Resources/Storyboards/Record/RecordStart.storyboard
  Weathy/Weathy/Sources/Models/SearchInformation/SearchRecentInfo.swift
  Weathy/Weathy/Sources/VCs/Main/MainVC.swift
  Weathy/Weathy/Sources/VCs/MainSearch/MainSearchVC.swift
  Weathy/Weathy/Sources/VCs/Record/RecordStartVC.swift
Labels: 황호, 🔧 fix

#53 Feat/41
  Weathy/Weathy.xcodeproj/project.pbxproj
  Weathy/Weathy/Resources/Assets.xcassets/search_img_brokenclouds.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/search_img_brokenclouds.imageset/search_img_brokenclouds.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_brokenclouds.imageset/search_img_brokenclouds@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_brokenclouds.imageset/search_img_brokenclouds@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_clearsky_day.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/search_img_clearsky_day.imageset/search_img_clearsky_day.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_clearsky_day.imageset/search_img_clearsky_day@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_clearsky_day.imageset/search_img_clearsky_day@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_clearsky_night.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/search_img_clearsky_night.imageset/search_img_clearsky_night.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_clearsky_night.imageset/search_img_clearsky_night@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_clearsky_night.imageset/search_img_clearsky_night@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_fewclouds_day.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/search_img_fewclouds_day.imageset/search_img_fewclouds_day.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_fewclouds_day.imageset/search_img_fewclouds_day@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_fewclouds_day.imageset/search_img_fewclouds_day@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_fewclouds_night.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/search_img_fewclouds_night.imageset/search_img_fewclouds_night.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_fewclouds_night.imageset/search_img_fewclouds_night@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_fewclouds_night.imageset/search_img_fewclouds_night@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_mist.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/search_img_mist.imageset/search_img_mist.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_mist.imageset/search_img_mist@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_mist.imageset/search_img_mist@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_rain.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/search_img_rain.imageset/search_img_rain.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_rain.imageset/search_img_rain@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_rain.imageset/search_img_rain@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_scatteredclouds.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/search_img_scatteredclouds.imageset/search_img_scatteredclouds.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_scatteredclouds.imageset/search_img_scatteredclouds@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_scatteredclouds.imageset/search_img_scatteredclouds@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_showerrain_day.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/search_img_showerrain_day.imageset/search_img_showerrain_day.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_showerrain_day.imageset/search_img_showerrain_day@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_showerrain_day.imageset/search_img_showerrain_day@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_showerrain_night.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/search_img_showerrain_night.imageset/search_img_showerrain_night.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_showerrain_night.imageset/search_img_showerrain_night@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_showerrain_night.imageset/search_img_showerrain_night@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_snow.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/search_img_snow.imageset/search_img_snow.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_snow.imageset/search_img_snow@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_snow.imageset/search_img_snow@3x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_thunderstorm.imageset/Contents.json
  Weathy/Weathy/Resources/Assets.xcassets/search_img_thunderstorm.imageset/search_img_thunderstorm.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_thunderstorm.imageset/search_img_thunderstorm@2x.png
  Weathy/Weathy/Resources/Assets.xcassets/search_img_thunderstorm.imageset/search_img_thunderstorm@3x.png
  Weathy/Weathy/Resources/Storyboards/MainSearch/MainSearch.storyboard
  Weathy/Weathy/Resources/Storyboards/Record/RecordStart.storyboard
  Weathy/Weathy/Resources/Storyboards/Tabbar/Tabbar.storyboard
  Weathy/Weathy/Sources/Cells/MainSearchTVCells/RecentTVC.swift
  Weathy/Weathy/Sources/Cells/MainSearchTVCells/SearchTVC.swift
  Weathy/Weathy/Sources/Models/Common/ClimateImage.swift
  Weathy/Weathy/Sources/VCs/MainSearch/MainSearchVC.swift
  Weathy/Weathy/Sources/VCs/OnBoarding/NickNameVC.swift
  Weathy/Weathy/Sources/VCs/Record/RecordStartVC.swift
Labels: 황호, 🔧 fix

#58 [bug] 닉네임 바꾸기 bug 수정
  Weathy/Weathy.xcodeproj/project.pbxproj
  Weathy/Weathy/Resources/APIServices/UserAPI/modifyUserService.swift
  Weathy/Weathy/Resources/Storyboards/OnBoarding/OnBoarding.storyboard
  Weathy/Weathy/Resources/Storyboards/Setting/Setting.storyboard
  Weathy/Weathy/Sources/Models/OnBoarding/온보딩_1.json
  Weathy/Weathy/Sources/Models/OnBoarding/온보딩_2.json
  Weathy/Weathy/Sources/Models/OnBoarding/온보딩_3.json
  Weathy/Weathy/Sources/VCs/OnBoarding/OnBoardingFirstVC.swift
  Weathy/Weathy/Sources/VCs/Setting/ChangeNickNameVC.swift
Labels: ✨ style, 황호
